### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by JudeTeremy** [JudeJeremy/PyxisStudios#1]
I'm pretty sure the reason it doesn't work is because of the change of variable name when new restaurants were added.

**Comment by JudeJeremy** [comment]
Yep, working on that right now.

**Comment by JudeTeremy** [comment]
Sounds good! Tell me if you need an eye on anything

**Comment by JudeJeremy** [comment]
Yep, just pushed the changes now. It is now fixed.
